### PR TITLE
Deeply stringify non-immutable objects

### PR DESCRIPTION
**Pull request by dsgkirkby**
`fast-deep-equal` uses an objects `toString` function to check equality if that object has a custom `toString` method: https://github.com/epoberezkin/fast-deep-equal/blob/master/src/index.jst#L52

This is a problem when we mix immutable and non-immutable objects, because they stringify to something like: `List [ DiscreteAttributeFilter { attributeInstance: [object Object], inclusive: true, type: "discrete"...`.

### CODE REVIEW

**Comment by dsgkirkby** [comment]
This will allow for an easier solution to [ch33021]

**Comment by holmari** [comment]
What's your thoughts on removing the toString call from fast-deep-equal? That whole "library" is like 50 lines of code anyway and we could just stick it in here if we wanted to.

**Comment by dsgkirkby** [comment]
I briefly considered that, but ended up deciding against it for 2 reasons:
1. I think we might actually depend on this toString action for immutable objects to be value-equal by fast-deep-equal's standards; I'm not sure if the internal structures they maintain would be guaranteed to be equal (I think it might be possible to have 2 vector tries with the same elements but different structure?)
2. this was allows us to contain ourselves to just 1 fork, not 2, so the maintenance burden is a bit less - won't have to manually pull and apply updates to fast-deep-equal if there are any.

**Comment by holmari** [comment]
on #2, I don't think it's a real issue with a "library" with 50 lines of code. Anyway, since immutable.js is also hardly maintained, I don't think it's an issue either way.

**Pull request merged**
